FROM lucee/lucee:7.1.0.48-SNAPSHOT-nginx-tomcat11.0-jdk25-temurin-noble
# COPY target/debugger-extension-*.lex /opt/lucee/server/lucee-server/deploy/
# COPY examples/docker/*.lco /opt/lucee/server/lucee-server/deploy/
