services:
  lucee:
    build:
      context: ../..
      dockerfile: examples/docker/Dockerfile
    environment:
      LUCEE_DAP_SECRET: my-secret
      LUCEE_DAP_PORT: 10000
      LUCEE_DAP_HOST: 0.0.0.0
      LUCEE_LOGGING_FORCE_APPENDER: console
      LUCEE_LOGGING_FORCE_LEVEL: info
      LUCEE_EXTENSIONS: org.lucee:debugger-extension:3.0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
      - "10000:10000"
    volumes:
      - ./app:/var/www
